<a href="https://colab.research.google.com/github/revanthmadasu/LifestyleWellbeing/blob/data-preprocessing/LifestyleWellbeing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the data

In [14]:
dataset = pd.read_csv('https://raw.githubusercontent.com/revanthmadasu/LifestyleWellbeing/master/Wellbeing_and_lifestyle_data_Kaggle.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Converting categorial data into numerical

Understanding which objects to convert

In [15]:
object_dataset = dataset.select_dtypes(include=['object']).copy()
object_dataset.head()

Timestamp DAILY_STRESS         AGE  GENDER
0    7/7/15            2    36 to 50  Female
1    7/7/15            3    36 to 50  Female
2    7/7/15            3    36 to 50  Female
3    7/7/15            3  51 or more  Female
4    7/7/15            1  51 or more  Female

Converting Timestamp using label encoding. "Finding and replacing" method would take forever. "One-hot encoder" method would creat a lot more unnecessary columns

In [16]:
dataset['Timestamp'] = dataset['Timestamp'].astype('category')
dataset['Timestamp'] = dataset['Timestamp'].cat.codes
dataset.head()

Timestamp  FRUITS_VEGGIES DAILY_STRESS  PLACES_VISITED  CORE_CIRCLE  \
0       5607               3            2               2            5   
1       5607               2            3               4            3   
2       5607               2            3               3            4   
3       5607               3            3              10            3   
4       5607               5            1               3            3   

   SUPPORTING_OTHERS  SOCIAL_NETWORK  ACHIEVEMENT  DONATION  BMI_RANGE  ...  \
0                  0               5            2         0          1  ...   
1                  8              10            5         2          2  ...   
2                  4              10            3         2          2  ...   
3                 10               7            2         5          2  ...   
4                 10               4            2         4          2  ...   

   SLEEP_HOURS  LOST_VACATION  DAILY_SHOUTING  SUFFICIENT_INCOME  \
0            7              5               5                  1   
1            8              2               2                  2   
2            8             10               2                  2   
3            5              7               5                  1   
4            7              0               0                  2   

   PERSONAL_AWARDS  TIME_FOR_PASSION  WEEKLY_MEDITATION         AGE  GENDER  \
0                4                 0                  5    36 to 50  Female   
1                3                 2                  6    36 to 50  Female   
2                4                 8                  3    36 to 50  Female   
3                5                 2                  0  51 or more  Female   
4                8                 1                  5  51 or more  Female   

   WORK_LIFE_BALANCE_SCORE  
0                    609.5  
1                    655.6  
2                    631.6  
3                    622.7  
4                    663.9  

[5 rows x 24 columns]

Using "Finding and replacing" method, since there are values only from 0 to 5, with a arbitrary value of 1/1/2000 in row 10007

In [17]:
dataset['DAILY_STRESS'] = dataset['DAILY_STRESS'].replace(['0','1','2','3','4','5'], [0,1,2,3,4,5])
dataset.head()

Timestamp  FRUITS_VEGGIES DAILY_STRESS  PLACES_VISITED  CORE_CIRCLE  \
0       5607               3            2               2            5   
1       5607               2            3               4            3   
2       5607               2            3               3            4   
3       5607               3            3              10            3   
4       5607               5            1               3            3   

   SUPPORTING_OTHERS  SOCIAL_NETWORK  ACHIEVEMENT  DONATION  BMI_RANGE  ...  \
0                  0               5            2         0          1  ...   
1                  8              10            5         2          2  ...   
2                  4              10            3         2          2  ...   
3                 10               7            2         5          2  ...   
4                 10               4            2         4          2  ...   

   SLEEP_HOURS  LOST_VACATION  DAILY_SHOUTING  SUFFICIENT_INCOME  \
0            7              5               5                  1   
1            8              2               2                  2   
2            8             10               2                  2   
3            5              7               5                  1   
4            7              0               0                  2   

   PERSONAL_AWARDS  TIME_FOR_PASSION  WEEKLY_MEDITATION         AGE  GENDER  \
0                4                 0                  5    36 to 50  Female   
1                3                 2                  6    36 to 50  Female   
2                4                 8                  3    36 to 50  Female   
3                5                 2                  0  51 or more  Female   
4                8                 1                  5  51 or more  Female   

   WORK_LIFE_BALANCE_SCORE  
0                    609.5  
1                    655.6  
2                    631.6  
3                    622.7  
4                    663.9  

[5 rows x 24 columns]

Using get_dummies method for 'AGE' & 'GENDER' category

In [18]:
dummy_col_df = pd.get_dummies(dataset, columns = ['AGE', 'GENDER'])
dummy_col_df.columns

Index(['Timestamp', 'FRUITS_VEGGIES', 'DAILY_STRESS', 'PLACES_VISITED',
       'CORE_CIRCLE', 'SUPPORTING_OTHERS', 'SOCIAL_NETWORK', 'ACHIEVEMENT',
       'DONATION', 'BMI_RANGE', 'TODO_COMPLETED', 'FLOW', 'DAILY_STEPS',
       'LIVE_VISION', 'SLEEP_HOURS', 'LOST_VACATION', 'DAILY_SHOUTING',
       'SUFFICIENT_INCOME', 'PERSONAL_AWARDS', 'TIME_FOR_PASSION',
       'WEEKLY_MEDITATION', 'WORK_LIFE_BALANCE_SCORE', 'AGE_21 to 35',
       'AGE_36 to 50', 'AGE_51 or more', 'AGE_Less than 20', 'GENDER_Female',
       'GENDER_Male'],
      dtype='object')

Shifting 'WORK_LIFE_BALANCE_SCORE' to the right

In [20]:
dummy_col_df = dummy_col_df[['Timestamp', 'FRUITS_VEGGIES', 'DAILY_STRESS', 'PLACES_VISITED',
       'CORE_CIRCLE', 'SUPPORTING_OTHERS', 'SOCIAL_NETWORK', 'ACHIEVEMENT',
       'DONATION', 'BMI_RANGE', 'TODO_COMPLETED', 'FLOW', 'DAILY_STEPS',
       'LIVE_VISION', 'SLEEP_HOURS', 'LOST_VACATION', 'DAILY_SHOUTING',
       'SUFFICIENT_INCOME', 'PERSONAL_AWARDS', 'TIME_FOR_PASSION',
       'WEEKLY_MEDITATION', 'AGE_21 to 35',
       'AGE_36 to 50', 'AGE_51 or more', 'AGE_Less than 20', 'GENDER_Female',
       'GENDER_Male', 'WORK_LIFE_BALANCE_SCORE']]
X = dummy_col_df.iloc[:, :-1].values
y = dummy_col_df.iloc[:, -1].values

In [21]:
print(X[0,:])

[5607 3 2 2 5 0 5 2 0 1 6 4 5 0 7 5 5 1 4 0 5 0 1 0 0 1 0]


In [23]:
print(X)

[[5607 3 2 ... 0 1 0]
 [5607 2 3 ... 0 1 0]
 [5607 2 3 ... 0 1 0]
 ...
 [3054 4 3 ... 0 0 1]
 [3055 1 1 ... 0 1 0]
 [3056 5 4 ... 0 1 0]]


In [24]:
print(y)

[609.5 655.6 631.6 ... 716.6 682.  651.4]
